### ISSUE TITLE
Network.clone() does not return a faithful copy of the original network

### ISSUE THREAD

**Issue by christianechevarria** [liquidcarrot/carrot#149]
### Description
The following code is failing and it shouldn't. I suspect this could be a failure to copy the exact weight values and biases which affects when a Network is reconstructed using `Network.fromJSON`. Individual nodes have their weights randomly initialized when created so an equality check at the network level may be failing because of this.

### Screenshots
![image](https://user-images.githubusercontent.com/23618650/62644147-759b2900-b917-11e9-8eb8-1001e76d52cb.png)

### Files
Network.js is the place to start, upon closer inspection I suspect that Node.js will have to be modified to produce the desired behavior.

### To Reproduce
Import mocha and chai, and write the code pictured above

### Tasks
Include specific tasks in the order they need to be done in. Include links to specific lines of code where the task should happen at.
- [ ] Review the Network.toJSON() & Network.fromJSON() methods inside of Network.js 
- [ ] Revise the way the input / output system works to allow for exact reconstruction of weights and biases
- [ ] Edit Network.js and Node.js as needed to make this happen

**Comment by christianechevarria** [comment]
## Update
Dropout is a property of one network but not the other

### Test:
![image](https://user-images.githubusercontent.com/23618650/62644751-cbbc9c00-b918-11e9-90de-3f3d25377a88.png)

### Output:
![Screenshot 2019-08-07 at 1 37 57 PM](https://user-images.githubusercontent.com/23618650/62644781-e3942000-b918-11e9-8c7e-a3a33b254de9.png)

**Comment by christianechevarria** [comment]
This StackOverflow answer to deep cloning an object in JavaScript can be useful:

https://stackoverflow.com/questions/122102/what-is-the-most-efficient-way-to-deep-clone-an-object-in-javascript

It seems like Lodash's `cloneDeep` is still one of the best methods to do this 

There is an experimental native method called "structured cloning" in Node but it has no browser support yet and doesn't seem to be part of the official spec

https://stackoverflow.com/questions/122102/what-is-the-most-efficient-way-to-deep-clone-an-object-in-javascript/10916838#10916838

Will probably use Lodash's `clondeDeep` for now

**Comment by christianechevarria** [comment]
The design of the test may also be influencing the results, testing for object equality can be a bit tricky.

Here is an excerpt from an article that covers testing Arrays and Objects with Chai:
![image](https://user-images.githubusercontent.com/23618650/62652487-805eb980-b929-11e9-92a8-8893027ede47.png)

Here's the article: https://medium.com/building-ibotta/testing-arrays-and-objects-with-chai-js-4b372310fe6d

**Comment by christianechevarria** [comment]
Fixed as of 84695a79900979fc46c81cd88eed315654e29ee7

Will need to open issues for the toJSON / fromJSON system as the phenomenon noted here applies

Closing this one though
