### ISSUE TITLE
Restore neuron's .type property to reliably track input, hidden, and output nodes

### ISSUE THREAD

**Issue by christianechevarria** [liquidcarrot/carrot#164]
### Description
Because we are not reliably tracking the type of nodes, basically whether they are an: `input`, `hidden`, or `output` we're experiencing bugs related to the management of network structure: #163 and the long-standing #51 

Sometime before commit 5b741fd3c91625e55b1dc1a7a112fdf4fddb7081 we removed the `.type` attribute of nodes but it's an elegant way to keep track of what the status of a node is. 

I think the long-standing bugs we've been having #51 and maybe even #34 are related to not setting and keeping the status of nodes current.

### Files
`src/architecture/Node`
`src/architecture/Group`
`src/architecture/Layer`
`src/architecture/Network`
`methods/mutation`

### To Reproduce
Run `.evolve` or `.mutate` with Network or Neat 

### Additional Notes
Throughout this it will be important to preserve Carrot's ability to make arbitrary shaped networks which may include connecting outputs to existing input and hidden nodes without becoming an output node itself

### Tasks
Include specific tasks in the order they need to be done in. Include links to specific lines of code where the task should happen at.
- [ ] Reintroduce types to neurons
- [ ] Set the .type attribute on all constructors
- [ ] Add code to update types when adding nodes, removing nodes, swapping, connecting, and disconnecting -- basically, updating the mutation code
- [ ] Remove any assumptions about nodes order or ensure that any mutations respect ordered assumptions

**Comment by raimannma** [comment]
Fixed in the typescript version
