### ISSUE TITLE
Parcel and building from source

### ISSUE THREAD

**Issue by missionz3r0** [liquidcarrot/carrot#215]
### Description
When running the build scripts there are a few problems and curiosities that come up.

The first problem is that the contribution document doesn't line up with what happens when we run build:src. The contribution document says we should get four files. index.js, index.min.js, index.browser.js, and index.browser.min.js The first two being for node, with the last two being for the browser. However, what we actually get when we build is index.min.js, index.browser.min.js, and index.browser.min.js.map. It's not a huge problem, but it is confusing to new folks coming into the project.

The second problem is that the current parcel set up builds for development, rather than production because it is missing the production flag in the config. It's a simple fix, but not one that is obvious if you aren't familiar with parcel. When the production flag isn't set, parcel builds for development mode which tries to open up a websocket with the server for what I think is hot-reloading. A useful feature but not what you're looking for when you're trying to build.

The third problem is documented on parcel. parcel-bundler/parcel#2128. With a potential [fix](https://github.com/parcel-bundler/parcel/issues/2128#issuecomment-531321257) in the same thread. But then if we want to implement that fix, the question is how far back do we want to go in version numbers? Or is there another way we want to fix this?

I'm thinking we could have two different directories one labeled dev and one for prod. That we'd put [here](https://github.com/liquidcarrot/carrot/tree/master/dist).

As for the parcel issue 2128, I'm less sure of how to properly handle it. I'm brand new to this project and would like to hear from those that have been around for their thoughts.

### Files
You can see the current items that you get out of the build [here](https://github.com/liquidcarrot/carrot/tree/master/dist), and [here](https://github.com/liquidcarrot/carrot/blob/master/CONTRIBUTING.md#file-sub-structure-scripts) is where the contribution guide says what you're supposed to see.

Then [here](https://github.com/liquidcarrot/carrot/blob/master/scripts/src.build.browser.js) is and [here](https://github.com/liquidcarrot/carrot/blob/master/scripts/src.build.node.js) is where you'd need to add the production flag.

### To Reproduce
Use "npm run build:src" and then try to include index.browser.min.js into a browser application.

### Tasks
- [ ] Determine how we want to separate building for development and production.
- [ ] Determine how we want to fix up the problem stemming from parcel-bundler/parcel#2128
- [ ] Fix the contribution guide so that it properly shows what is built, but that may need to wait until we figure out how we want to deal with problems two and three. Which would be done [here](https://github.com/liquidcarrot/carrot/blob/master/CONTRIBUTING.md#file-sub-structure-scripts)

**Comment by raimannma** [comment]
There is another question to ask:

Webpack or Parcel ?

Right now both are implemented, which is very bad.

**Comment by missionz3r0** [comment]
@raimannma Well, just tried running webpack. It's not currently working correctly because it's pointing at a file doesn't exist anymore. Which is ./src/carrot.js. If we switch it to the correct file ./src/index.js it works better.

Though I can see that it has options to build for production, I'm not sure how to get it to use them.

Using the flag env.production doesn't seem to work. Nor does --mode=production.

**Comment by missionz3r0** [comment]
As for webpack or parcel. I'm unsure of which would be the better tool. I'm familiar with webpack, but not parcel. What are the advantages of using parcel over webpack?

**Comment by christianechevarria** [comment]
As far as I understand, parcel is a bit faster and is more friendly to the ES2015 module system (which we may want to explore in the future to have true isomorphic code), but for right now I think it's giving us more headache that it's worth. The changes that introduced parcel in are clustered in a series of commits from c09adef487927b72b4110bad07bdef647dee0635 to f3c334df2da1ba288a2e22a9715557bd9200a0f2 it seems. We might be able to just "roll these back" (although we may have to do this manually, not sure what the git-way would be right now) and keep going with webpack for now which was really working fine.

**Comment by missionz3r0** [comment]
I tried that. Though I was having a similar issue of figuring out how to run it different for production/development.

@christianechevarria

**Comment by christianechevarria** [comment]
> I tried that. Though I was having a similar issue of figuring out how to run it different for production/development.
> 
> @christianechevarria

If I'm understanding your question correctly (I suspect I might not be), inside of the [`webpack.config.js`](https://github.com/liquidcarrot/carrot/blob/master/webpack.config.js) we're using something called `parallel-webpack.createVariants` which automatically builds production and development files for various targets so that you just have to call webpack from the command line and it's done for you -- the relevant code for this is in added below https://github.com/liquidcarrot/carrot/blob/3a4a96764ab26e4cf03786f48c733bf5d83c2205/webpack.config.js#L55-L59

**Comment by missionz3r0** [comment]
Ah, maybe I'm just dropping the wrong file into place then. I'll tinker some more with it.

**Comment by christianechevarria** [comment]
Hi all, just making sure if this issue should still be open, I believe we resolved in the [Gitter chat](https://gitter.im/carrot-ai/community) to continue using Webpack and roll back these changes correct?

**Comment by missionz3r0** [comment]
Yeah we can close down the issue. Long as we know that we're going to roll back to webpack.
